# This file contains tasks for installation of 'nvm'. It expects to have a input variable called 'user' 
- name: "NVM | Install | Install 'nvm' for user"
  block:

  - name: "NVM | Install | Verify user exists"
    ansible.builtin.user:
      name: "{{ user.name }}"
      state: present
    register: user_info
    check_mode: true 

  - name: "NVM | Install | Fail if user does not exist"
    ansible.builtin.fail:
      msg: "No user {{ user.name }} found!"
    when: user_info.changed

  - name: "NVM | Install | Set remote repository url"
    ansible.builtin.set_fact:
      nvm_remote_git_url: "{{ nvm.source_url | default(nvm_source_url) }}.git" 
  
  - name: "NVM | Install | Verify version exists remotely"
    ansible.builtin.command: "git ls-remote {{ nvm_remote_git_url }} {{ user.version }}"
    register: nvm_version_info 
    changed_when: False
  
  - name: "NVM | Install | Fail if version is not found remotely"
    ansible.builtin.fail:
      msg: "No nvm version '{{ user.version }}' found remotely!"
    when: nvm_version_info | length == 0

  - name: "NVM | Install | Set installation path variable"
    ansible.builtin.set_fact:
      nvm_installation_path: "{{ user_info.home }}/{{ user.path | default('.nvm') }}" 

  - name: "NVM | Install | Ensure installation path"
    ansible.builtin.file:
      path: "{{ nvm_installation_path }}"
      state: directory
      modification_time: preserve
      access_time: preserve
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0755

  - name: "NVM | Install | Set local installation git path"
    ansible.builtin.set_fact:
      nvm_installation_git_path: "{{ nvm_installation_path }}/.git" 

  - name: "NVM | Install | Check for local respository existence"
    ansible.builtin.stat:
      path: "{{ nvm_installation_git_path }}"
    register: nvm_directory_git

  - name: "NVM | Install | Clone remote repository version"
    become_user: "{{ user.name }}"
    ansible.builtin.git:
      repo: "{{ nvm_remote_git_url }}"
      dest: "{{ nvm_installation_path }}"
      version: "{{ user.version }}"
      # otherwise ssh based submodules will be triggered, which might break if no ssh keys 
      # are found on the system. This is due to this role not using ssh for git repository
      # cloning, but the submodules for nvm (as of the time of this writing) does.
      recursive: false
      depth: 1
    when: not nvm_directory_git.stat.exists
  
  - name: "NVM | Install | Fetch remote repository version"
    become_user: "{{ user.name }}"
    ansible.builtin.command: "git --git-dir={{ nvm_installation_git_path }} --work-tree={{ nvm_installation_path }} fetch origin tag {{ user.version }} --depth=1"
    when: nvm_directory_git.stat.exists

  - name: "NVM | Install | Checkout remote repository version"
    become_user: "{{ user.name }}"
    ansible.builtin.command: "git -c advice.detachedHead=false --git-dir={{ nvm_installation_git_path }} --work-tree={{ nvm_installation_path }} checkout -f --quiet FETCH_HEAD"
    when: nvm_directory_git.stat.exists

  - name: "NVM | Install | Compress local repository"
    become_user: "{{ user.name }}"
    ansible.builtin.command: "git --git-dir={{ nvm_installation_git_path }} --work-tree={{ nvm_installation_path }} reflog expire --expire=now --all"

  - name: "NVM | Install | Clean local repository"
    become_user: "{{ user.name }}"
    ansible.builtin.command: "git --git-dir={{ nvm_installation_git_path }} --work-tree={{ nvm_installation_path }} gc --auto --aggressive --prune=now"

  - name: "NVM | Install | Copy environment file"
    become_user: "{{ user.name }}"
    ansible.builtin.copy:
      src: nvm.sh
      dest: "{{ user_info.home }}/.env.d"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0644
      force: no
  
  - name: "NVM | Install | Set location in environment file"
    become_user: "{{ user.name }}"
    ansible.builtin.lineinfile:
      path: "{{ user_info.home }}/.env.d/nvm.sh"
      regexp: "^export NVM_DIR="
      line: "export NVM_DIR={{ nvm_installation_path }}"
