- name: Assert necessary inputs
  ansible.builtin.import_tasks: assertions/assert.yml
  run_once: yes
  delegate_to: localhost


- name: Install 'nvm' for users
  ansible.builtin.include_tasks: install.yml
  loop: "{{ nvm.users }}"
  loop_control:
    loop_var: user
  when: nvm.users | length > 0
  